### ISSUE TITLE
Fake Inventory and Buttons mode improvements

### ISSUE THREAD

**Issue by Fixer-007** [cx384/storage_interface#2]
Currently those modes are very cryptic and inefficient in terms of space use:
1) Button mode
![default](https://user-images.githubusercontent.com/16494741/30757815-aa4e867e-9fd8-11e7-99c8-21db0dc40323.png)
* moving numbers in buttons corners
* moving buttons closer to each other to save space
2) Fake Inventory mode
![default](https://user-images.githubusercontent.com/16494741/30758014-6fa1be78-9fd9-11e7-894d-bbec80fd8169.png)
* Fake Inventory should look just like "Actual Inventory" like on image below, but with items condensed
![default](https://user-images.githubusercontent.com/16494741/30757915-0683f488-9fd9-11e7-92d2-ed4658d9fd08.png)

**Comment by cx384** [comment]
- moving numbers

As far as I know this is not possible, because in formspec labels can't be displayed above buttons or inventory lists and nowadays an itemstack can't be bigger then its max stack.
But if you know a way to to this please tell it to me or make a pull request.
What do you think about an option to disable this numbers?

- save space

Currently buttons are at the same place as items in the fake inventory mode.
Should they be smaller or closer to each other?

If you want to see the item count the vertical space is necessary, because if you squash the lines together you don't get enough space to add one more line.

**Comment by Fixer-007** [comment]
>As far as I know this is not possible, because in formspec labels can't be displayed above buttons or inventory lists and nowadays an itemstack can't be bigger then its max stack.

Maybe @rubenwardy or other formspec experts have an idea

>What do you think about an option to disable this numbers?

Stack size numbers in fake inventory mode should be hidden by default, they only confuse and clutter interface.

>Currently buttons are at the same place as items in the fake inventory mode. Should they be smaller or closer to each other?

This needs solving numbers on buttons/in inventory problem first, this way you can condense it to look like actual inventory (15x7 vs 15x5 (on my screen)).
